# ---------------------------------------------
# ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
# Source: backend/db/schemas/__init__.py, backend/db/data_models/__init__.py
# Generated by: backend/db/scripts/generate_sqlmodel_from_sql.py
# Time: 2025-07-07 14:56:44 PDT
# ---------------------------------------------

import enum
from datetime import datetime, timezone
from typing import Any, Optional, cast
from uuid import UUID, uuid4

from sqlalchemy.dialects.postgresql import JSON
from sqlmodel import Column, Enum, Field, SQLModel


def enum_values(enum_class: type[enum.Enum]) -> list[str]:
    """Get values for enum."""
    return [status.value for status in enum_class]


class UserProvidedOccasion(str, enum.Enum):
    WEDDING = "wedding"
    BIRTHDAY = "birthday"
    ANNIVERSARY = "anniversary"
    OTHER = "other"


class DAOAssets(SQLModel, table=True):
    __tablename__ = cast("Any", "assets")
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    user_id: UUID
    asset_key_original: str
    asset_key_display: Optional[str] = Field(default=None)
    asset_key_llm: Optional[str] = Field(default=None)
    metadata_json: Optional[dict[str, Any]] = Field(default=None, sa_type=JSON)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    original_photobook_id: Optional[UUID] = Field(default=None)


class DAOJobs(SQLModel, table=True):
    __tablename__ = cast("Any", "jobs")
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    job_type: str
    status: str
    input_payload: Optional[dict[str, Any]] = Field(default=None, sa_type=JSON)
    result_payload: Optional[dict[str, Any]] = Field(default=None, sa_type=JSON)
    error_message: Optional[str] = Field(default=None)
    user_id: Optional[UUID] = Field(default=None)
    photobook_id: Optional[UUID] = Field(default=None)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    started_at: Optional[datetime] = Field(default=None)
    completed_at: Optional[datetime] = Field(default=None)


class DAOPages(SQLModel, table=True):
    __tablename__ = cast("Any", "pages")
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    photobook_id: Optional[UUID] = Field(default=None)
    page_number: int
    user_message: Optional[str] = Field(default=None)
    layout: Optional[str] = Field(default=None)
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    user_message_alternative_options: Optional[dict[str, Any]] = Field(
        default=None, sa_type=JSON
    )


class DAOPagesAssetsRel(SQLModel, table=True):
    __tablename__ = cast("Any", "pages_assets_rel")
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    page_id: Optional[UUID] = Field(default=None)
    asset_id: Optional[UUID] = Field(default=None)
    order_index: Optional[int] = Field(default=None)
    caption: Optional[str] = Field(default=None)


class DAOPhotobooks(SQLModel, table=True):
    __tablename__ = cast("Any", "photobooks")
    id: UUID = Field(primary_key=True, default_factory=uuid4)
    user_id: UUID
    title: str
    caption: Optional[str] = Field(default=None)
    theme: Optional[str] = Field(default=None)
    status: Optional[str]
    created_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    updated_at: Optional[datetime] = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )
    user_provided_occasion: Optional[UserProvidedOccasion] = Field(
        default=None,
        sa_column=Column(
            Enum(UserProvidedOccasion, nullable=True, values_callable=enum_values)
        ),
    )
    user_provided_occasion_custom_details: Optional[str] = Field(default=None)
    user_provided_context: Optional[str] = Field(default=None)


class DAOUsers(SQLModel, table=True):
    __tablename__ = cast("Any", "users")
    id: UUID = Field(primary_key=True)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    email: Optional[str] = Field(default=None)
    phone: Optional[str] = Field(default=None)
    email_confirmed_at: Optional[datetime] = Field(default=None)
    phone_confirmed_at: Optional[datetime] = Field(default=None)
    name: Optional[str] = Field(default=None)
    role: str
