# ---------------------------------------------
# ⚠️ AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
# Source: backend/db/data_models/__init__.py
# Generated by: backend/db/scripts/generate_crud_schemas.py
# Time: 2025-07-07 14:56:45 PDT
# ---------------------------------------------

from datetime import datetime
from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict

from db.data_models import UserProvidedOccasion


class WritableModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)  # used for Create/Update


class DAOAssetsCreate(WritableModel):
    user_id: UUID
    asset_key_original: str
    asset_key_display: Optional[str]
    asset_key_llm: Optional[str]
    metadata_json: Optional[dict[str, Any]]
    original_photobook_id: Optional[UUID]


class DAOAssetsUpdate(WritableModel):
    user_id: Optional[UUID] = None
    asset_key_original: Optional[str] = None
    asset_key_display: Optional[str] = None
    asset_key_llm: Optional[str] = None
    metadata_json: Optional[dict[str, Any]] = None
    original_photobook_id: Optional[UUID] = None


class DAOJobsCreate(WritableModel):
    job_type: str
    status: str
    input_payload: Optional[dict[str, Any]]
    result_payload: Optional[dict[str, Any]]
    error_message: Optional[str]
    user_id: Optional[UUID]
    photobook_id: Optional[UUID]
    started_at: Optional[datetime]
    completed_at: Optional[datetime]


class DAOJobsUpdate(WritableModel):
    job_type: Optional[str] = None
    status: Optional[str] = None
    input_payload: Optional[dict[str, Any]] = None
    result_payload: Optional[dict[str, Any]] = None
    error_message: Optional[str] = None
    user_id: Optional[UUID] = None
    photobook_id: Optional[UUID] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None


class DAOPagesCreate(WritableModel):
    photobook_id: Optional[UUID]
    page_number: int
    user_message: Optional[str]
    layout: Optional[str]
    user_message_alternative_options: Optional[dict[str, Any]]


class DAOPagesUpdate(WritableModel):
    photobook_id: Optional[UUID] = None
    page_number: Optional[int] = None
    user_message: Optional[str] = None
    layout: Optional[str] = None
    user_message_alternative_options: Optional[dict[str, Any]] = None


class DAOPagesAssetsRelCreate(WritableModel):
    page_id: Optional[UUID]
    asset_id: Optional[UUID]
    order_index: Optional[int]
    caption: Optional[str]


class DAOPagesAssetsRelUpdate(WritableModel):
    page_id: Optional[UUID] = None
    asset_id: Optional[UUID] = None
    order_index: Optional[int] = None
    caption: Optional[str] = None


class DAOPhotobooksCreate(WritableModel):
    user_id: UUID
    title: str
    caption: Optional[str]
    theme: Optional[str]
    status: Optional[str]
    user_provided_occasion: Optional[UserProvidedOccasion]
    user_provided_occasion_custom_details: Optional[str]
    user_provided_context: Optional[str]


class DAOPhotobooksUpdate(WritableModel):
    user_id: Optional[UUID] = None
    title: Optional[str] = None
    caption: Optional[str] = None
    theme: Optional[str] = None
    status: Optional[str] = None
    updated_at: Optional[datetime] = None
    user_provided_occasion: Optional[UserProvidedOccasion] = None
    user_provided_occasion_custom_details: Optional[str] = None
    user_provided_context: Optional[str] = None


class DAOUsersCreate(WritableModel):
    email: Optional[str]
    phone: Optional[str]
    email_confirmed_at: Optional[datetime]
    phone_confirmed_at: Optional[datetime]
    name: Optional[str]
    role: str


class DAOUsersUpdate(WritableModel):
    email: Optional[str] = None
    phone: Optional[str] = None
    email_confirmed_at: Optional[datetime] = None
    phone_confirmed_at: Optional[datetime] = None
    name: Optional[str] = None
    role: Optional[str] = None
